### ISSUE TITLE
missing repo https://github.com/p3lim/rudder 

### ISSUE THREAD

**Issue by joyshmitz** [k8s-at-home/awesome-home-kubernetes#73]
# Details

**What steps did you take and what happened:**

**What did you expect to happen:**
go to links https://github.com/p3lim/rudder

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
Looks like that repository no longer exists. @p3lim do you want us to remove it?

**Comment by p3lim** [comment]
Go ahead.
